package com.controller;

public enum Action {
	AUTHENTICATION, NEW_USER, GET_SHEDULE, GET_APPROPRIATE_JOURNEYS, BUY_TICKET, REGISTER_PASSENGER, FIND_JOURNEY,
	CHECK_TICKETS, OUT, CREATE_ROUTE, CREATE_START_FINISH, INSERT_STATION, GET_TIME_AND_COST, BUILD_NEW_ROUTE, CREATE_TRAIN,
	GET_ROUTES_INFO, PLAN_JOURNEY, CREATE_STATION, GET_ALL_JOURNEYS_BRIEF, GET_PASSENGERS, RESET_DB, INIT_DB, USER_VALIDATION
}
